language: node_js

node_js:
  - node
  - lts/*

cache:
  directories:
    - node_modules

script:
  - npm run test

#@todo Enable after coverage is actually setup.
#after_script:
#  - cat ./coverage/lcov.info | coveralls
